### PR TITLE
ZhaoyangLIu's V1

### PR DESCRIPTION
**Pull request by zhaoyang-liu**

### CODE REVIEW

**Comment by lloydlentz** [comment]
Were you able to get this to run?  There is an indentation error on line 24.  Also, there is no writeup.  Please explain

**Comment by zhaoyang-liu** [comment]
Dear professor,
I am so sorry that I don't check this email frequently since I also get
your email from another  email address. I made some changes before I
uploaded to github without checking. And now I get stuck for the current
version. Could I talk about that with you in class or before class?
Thank you!

2015-02-23 20:40 GMT-06:00 Lloyd Cledwyn notifications@github.com:

**Comment by lloydlentz** [comment]
Yes, no problem.  I am planning on flipping the lecture today so that we
have time to spend working on the assignments.

**Comment by zhaoyang-liu** [comment]
Thank you very much! See you then.

2015-02-25 16:36 GMT-06:00 Lloyd Cledwyn notifications@github.com:

**Comment by lloydlentz** [comment]
grade on CourseCal

**Pull request closed without merging**
